### ISSUE TITLE
Downgrade to 5.4

### ISSUE THREAD

**Issue by VQFCOSTA-Infortech** [AlanMartines/monitoramento-sefaz-zabbix-grafana#2]
**No arquivo YAML altere a versão de 7.0 para 5.4 e mude a tag do grupo, depois de criar os grupos manualmente, realize a importação**
Obs: Lembre-se de não marcar a opção de CRIAR NOVO GRUPO no zabbix, apenas editar o atual existente.

### Atual:
```
zabbix_export:
  version: '7.0'
  host_groups:
```

### Alteração: 
```
zabbix_export:
  version: '5.4'
  groups:
```

### Antes de importar os arquivos YAML, crie os grupos manualmente.

Grupo de Hosts: Monitoramento Sefaz
Grupo de Templates: Templates/Sefaz

**Comment by AlanMartines** [comment]
> **No arquivo YAML altere a versão de 7.0 para 5.4 e mude a tag do grupo, depois de criar os grupos manualmente, realize a importação** Obs: Lembre-se de não marcar a opção de CRIAR NOVO GRUPO no zabbix, apenas editar o atual existente.
> 
> ### Atual:
> ```
> zabbix_export:
>   version: '7.0'
>   host_groups:
> ```
> 
> ### Alteração:
> ```
> zabbix_export:
>   version: '5.4'
>   groups:
> ```
> 
> ### Antes de importar os arquivos YAML, crie os grupos manualmente.
> Grupo de Hosts: Monitoramento Sefaz Grupo de Templates: Templates/Sefaz

Bom dia,

Vou adicinar no README
